export const REQUESTING_QUESTIONS = 'REQUESTING_QUESTIONS';
export const REQUESTING_QUESTIONS_ERROR = 'REQUESTING_QUESTIONS_ERROR';
export const RECEIVED_QUESTIONS = 'RECEIVED_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const ADD_ANSWER = 'ADD_ANSWER';
export const REMOVE_ANSWER = 'REMOVE_ANSWER';
