import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import Answer from './answer-item.component';
import axios from 'axios';
import { MDBContainer, MDBCol, MDBRow, MDBBtn, MDBIcon } from 'mdbreact';
import '../Questions/questions-list.component.scss'
var moment = require('moment');

export default class AnswersList extends Component {
    constructor(props) {
        super(props);

        this.state = {
            question: []
        }
    }

    componentDidMount = () => {
        axios.get('/questions/' + this.props.match.params.qid)
            .then(response => {
                this.setState({
                    question: response.data
                });
            })
            .catch(error => {
                console.log("Error: " + error);
            });
    }

    deleteAnswer = (id) => {
        axios.delete('/questions/' + id)
            .then(response => console.log(response))

        // Update state (_id is autogenerated by MongoDB)
        this.setState({
            questions: this.state.questions.filter(question => question._id !== id)
        })
    }

    createAnswerPanels = () => {
        if (this.state.question.answers !== undefined) {
            return this.state.question.answers.map(answer => {
                return (
                    <Answer 
                        answer={answer}
                        deleteAnswer={this.deleteAnswer}
                        key={answer._id}
                    />
                );
            })
        } 
    }

    render() {
        return (
            <MDBContainer>
                <MDBRow>
                    <MDBCol md="4" />
                    <MDBCol md="4">
                        <Link className="text-center" to="/create">
                            <MDBBtn className="interviewClubBtn" color="pink" size="md" style={{ width: "100%" }}>
                                <MDBIcon icon="rocket" style={{ marginRight: "10px" }} />
                                Add New Answer
                            </MDBBtn>  
                        </Link>  
                    </MDBCol>
                    <MDBCol md="4" />
                </MDBRow>
                <MDBRow className="d-flex justify-content-center">
                    <h1>{ this.state.question.text }</h1>
                </MDBRow>
                { this.createAnswerPanels() }  
            </MDBContainer>
        )
    }
}